-- Create tables if not exists (Optional if using hibernate ddl-auto: update/create)
CREATE TABLE IF NOT EXISTS RGON_M (
    RGON_CD INT PRIMARY KEY,
    RGON_NM VARCHAR(40),
    DELETE_FLG VARCHAR(1),
    RGON_USE_TYP VARCHAR(1),
    DISP_ORDER INT
);

CREATE TABLE IF NOT EXISTS PREF_M (
    PREF_CD INT PRIMARY KEY,
    PREF_NM VARCHAR(40),
    DELETE_FLG VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS CONTACT_M (
    CONTACT_CD VARCHAR(20) PRIMARY KEY,
    CONTACT_NM VARCHAR(100),
    CONTACT_KN VARCHAR(200),
    TEL_NO VARCHAR(13),
    PREF_CD INT,
    RGON_CD INT,
    DELETE_FLG VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS URL_M (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTACT_CD VARCHAR(20),
    URL_ADDR VARCHAR(256),
    DELETE_FLG VARCHAR(1)
);

-- Insert Sample Data
INSERT INTO RGON_M (RGON_CD, RGON_NM, DELETE_FLG, RGON_USE_TYP, DISP_ORDER) VALUES
(1, 'Kanto', '0', '1', 1),
(2, 'Kansai', '0', '1', 2);

INSERT INTO PREF_M (PREF_CD, PREF_NM, DELETE_FLG) VALUES
(13, 'Tokyo', '0'),
(27, 'Osaka', '0');

INSERT INTO CONTACT_M (CONTACT_CD, CONTACT_NM, CONTACT_KN, TEL_NO, PREF_CD, RGON_CD, DELETE_FLG) VALUES
('CD001', 'Cong ty Nhat A', 'コンパニーA', '09011112222', 13, 1, '0'),
('CD002', 'Cong ty Nhat B', 'コンパニーB', '09033334444', 27, 2, '0');

INSERT INTO URL_M (CONTACT_CD, URL_ADDR, DELETE_FLG) VALUES
('CD001', 'https://companyA.jp', '0'),
('CD001', 'https://support.companyA.jp', '0');
